#!/bin/bash
cd "$(dirname "$0")/.."

if ! hyprctl clients -j | jq -e '.[] | select(.title == "Emoji Kbd")' > /dev/null; then
    width=$(python src/config.py terminal.width)
    height=$(python src/config.py terminal.height)
    font_size=$(python src/config.py terminal.font_size)
    kitty --title "Emoji Kbd" -o remember_window_size=no \
        -o initial_window_width=${width}c -o initial_window_height=${height}c \
        -o font_size=${font_size} \
        --hold=no -e python src/termkbd.py --daemon &
else
    hyprctl dispatch movetoworkspace '+0,title:^Emoji Kbd$'
fi
