#!/bin/bash
cd "$(dirname "$0")/.."
source .venv/bin/activate

if ! hyprctl clients -j | jq -e '.[] | select(.title == "Emoji Kbd")' > /dev/null; then
    if ! python src/config.py > /dev/null; then
        kitty --title "Emoji Kbd" -o remember_window_size=no \
            -o initial_window_width=80c -o initial_window_height=24c \
            --hold=yes -e python src/config.py
        exit 0
    fi
    width=$(python src/config.py terminal.width)
    height=$(python src/config.py terminal.height)
    font_size=$(python src/config.py terminal.font_size)
    kitty --title "Emoji Kbd" -o remember_window_size=no \
        -o initial_window_width=${width}c -o initial_window_height=${height}c \
        -o font_size=${font_size} \
        --hold=yes -e python src/termkbd.py --daemon &
else
    MINOR_VERSION=$(hyprctl version | grep -oP 'Tag: v0\.\K[0-9]+')
    if [ "$MINOR_VERSION" -lt 55 ]; then
        hyprctl dispatch -- "hl.dsp.workspace.toggle_special('emoji')"
    else
        hyprctl dispatch -- 'hl.dsp.window.move({ workspace = hl.get_active_workspace().id, window = "title:^(Emoji Kbd)$", follow = true })'
    fi
fi
